### ISSUE TITLE
Fehlercode 500

### ISSUE THREAD

**Issue by renepetermann289** [PHT-Medic/central-deployment#1]
Nach der Installation der APP erhalte ich über die URL den Fehlercode 500 (Invalid URL). Container laufen und werden auch an den richtigen Port weitergeleitet. Hat jemand eine Idee, was hier das Problem sein kann?

    d7254ab3eee   ghcr.io/pht-medic/central:latest     "/bin/sh ./entrypoin…"   5 minutes ago    Up 5 minutes              0.0.0.0:3003->3000/tcp, :::3003->3000/tcp                            central-train-manager
    5cf8ee246b7c   ghcr.io/pht-medic/central:latest     "/bin/sh ./entrypoin…"   5 minutes ago    Up 5 minutes              0.0.0.0:3001->3000/tcp, :::3001->3000/tcp                            central-realtime
    8261000c20ba   ghcr.io/pht-medic/central:latest     "/bin/sh ./entrypoin…"   5 minutes ago    Up 5 minutes              0.0.0.0:3002->3000/tcp, :::3002->3000/tcp                            central-api
    793f6087c8d4   ghcr.io/pht-medic/central:latest     "/bin/sh ./entrypoin…"   5 minutes ago    Up 5 minutes              0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                            central-ui
    4d47d510efe7   ghcr.io/authup/authup:latest         "/bin/sh ./entrypoin…"   5 minutes ago    Up 5 minutes (healthy)    3001-3002/tcp, 0.0.0.0:3010->3000/tcp, :::3010->3000/tcp             central-authup

**Comment by tada5hi** [comment]
Hey @renepetermann289,
das liegt unteranderem daran, dass bei der migration zu v3 die env variablen für das frontend mit `NUXT_PUBLIC` geprefixed werden müssen.
Ich hab die README.md angepasst.
Ich hoffe, dass jetzt alles klappt :)

see https://github.com/PHT-Medic/central-deployment/commit/d77d5c13fb29e485086e2dd4a0b979834c320541

**Comment by renepetermann289** [comment]
Wunderbar, ich danke dir.
